name: Test edtf-convert

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.6, 3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: pip install tox pytest
      - name: Run tox
        # Run tox using the version of Python in `PATH`
        run: tox -e py
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 --max-line-length=99 --statistics edtf_convert tests setup.py
