name: Test edtf-convert

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.6, 3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run:  |
          python -m pip install --upgrade pip
          pip install pytest flake8
      - name: Lint with flake8
        run: |
          flake8 --max-line-length=99 --statistics edtf_convert tests setup.py
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings.
          flake8 --count --exit-zero --max-complexity=10 --max-line-length=100 --statistics edtf_convert tests setup.py
      - name: Run the tests
        run: |
            pytest
